version: '3.3'

services:
  postgres:
    restart: always
    privileged: true
    image: postgres:10.7-alpine
    # container_name: postgres
    command: postgres -c max_connections=100 -c shared_buffers=200MB
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgres:/var/lib/postgresql/data